# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bffc7c73ccc58f2f6a9e7c552820ceedc3086d14eff90836c01780856566944b658111ee8bf6ecb366ebf747938d27a145df751d86391baec2ec1aac331d78cf

test:
  secret_key_base: bde419858f5161a3b32337784429b9097d895bc406c1b6ca12d3933bfa7cf7644a44aeaeb93578823d9a46d089a34578a1621f13fe96253cf01125564fd37b77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
